### ISSUE TITLE
Question: usage with `setup.py` and `requirements.dev.txt`

### ISSUE THREAD

**Issue by samjewell** [adamchainz/pip-lock#169]
Thanks very much for this tool - it looks valuable.

I have two questions, which I couldn't answer from the Readme/documentation:

1. Can I use this tool with requirements listed in `setup.py` (as [described here](https://beam.apache.org/documentation/sdks/python-pipeline-dependencies/#multiple-file-dependencies:~:text=Note%3A%20If%20you%20created%20a%20requirements.txt,the%20setup%20call%20(in%20step%201).))? If so, how?
2. Can I use it with `requirements.dev.txt`? How can I check the dev requirements in the dev environment, but only the prod requirements in the prod environment? In this case I have a flask app - but I'm not sure that flask knows which environment it is running in. Would you simply follow [this convention](https://stackoverflow.com/a/44951470/1358187), and do `if os.environ['ENV'] == 'prod':` to switch between the two requirements files?

Thanks!

**Comment by adamchainz** [comment]
1. It doesn't work with `setup.py` but you can use a setup.py setup that reads from a requirements.txt file.

2. Yes, pass different filenames to `check_requirements`. I wouldn't recommend having different dependencies in dev versus prod though, it can make your deploys less predictable.
